### PR TITLE
Fix invalid HTML code with links in headers.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by vladikoff** [comment]
Hm are you making them empty? that might be a bad idea

**Comment by XhmikosR** [comment]
I tested this in our docs and seems to be fine. Do you want me to use a `&nbsp;`?

**Comment by vladikoff** [comment]
>  Do you want me to use a &nbsp;?

Hm nah, I'll double check...

**Comment by XhmikosR** [comment]
@vladikoff: just pinging for when you have some time.

**Pull request merged**
